/*******************************************************//**
@class      Class Name
@brief      Description of the class
@testClass  Test Class Name
@author     Developer Name (leehildebrand)
@version    @version    2/13/18   Developer Name (leehildebrand) - Purpose of the change
@bug        No known defects.
@todo       None.
@copyright  (c)2018 EMS.  All Rights Reserved. Unauthorized use is prohibited.
***********************************************************/
public with sharing class MediaURL {
    public String mediaURL{get;set;}
}